# Generated by Django 4.2.22 on 2025-06-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hear_about",
            field=models.CharField(blank=True, null=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
