# Generated by Django 4.2.22 on 2025-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_hear_about_user_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="purpose",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
