# Generated by Django 4.2.22 on 2025-06-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_hear_about_user_job_title'),
    ]

    operations = [
    ]
