# Generated by Django 4.2.22 on 2025-06-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250616_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
    ]
