# Generated by Django 4.2.22 on 2025-06-18 13:45

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (Max size: 5MB, Formats: JPG, PNG, GIF)', null=True, upload_to=accounts.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='purpose',
            field=models.TextField(blank=True, help_text='What do you plan to use this system for?', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='hear_about',
            field=models.CharField(blank=True, help_text='How did you hear about us?', max_length=200, null=True),
        ),
    ]
