# Generated by Django 4.2.22 on 2025-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar_user_job_title_user_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_code',
            field=models.CharField(blank=True, help_text='Current 6-digit MFA code', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_code_expires',
            field=models.DateTimeField(blank=True, help_text='When the MFA code expires', null=True),
        ),
    ]
