# Generated by Django 4.2.22 on 2025-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_mfa_code_user_mfa_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of backup codes for MFA'),
        ),
    ]
