# Generated by Django 4.2.22 on 2025-07-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_mfa_backup_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_verified',
            field=models.BooleanField(default=False, help_text='Whether MFA has been verified in current session'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
