# Generated by Django 4.2.22 on 2025-06-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20250616_1133'),
    ]

    operations = [
        # Rename 'name' field to 'key' on Tag model
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='key',
        ),
        # Add 'value' field to Tag model
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(blank=True, help_text='Tag value (optional)', max_length=100),
        ),
        # Update unique_together constraint
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('key', 'value', 'created_by')},
        ),
        # Update ordering in Meta
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['key', 'value']},
        ),
    ]
