# Generated by Django 4.2.22 on 2025-07-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentversion_reason_alter_documentversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='short_id',
            field=models.CharField(blank=True, editable=False, help_text='Short, unique, human-friendly document ID', max_length=12, unique=True),
        ),
    ]
