# Generated by Django 4.2.22 on 2025-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_add_document_versioning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
