# Generated by Django 4.2.22 on 2025-07-09 18:58

import django.core.validators
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_document_content_remove_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.document_version_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
